#!/bin/bash
# Deploy Prod + Dev on SAME EC2 instance with shared Nginx
# Prod: app.domain.com -> api:5001 (serves both API + frontend in Docker)
# Dev:  dev.domain.com -> ports 5005, 3002
#
# Usage:
#   export EC2_IP=13.233.0.43
#   export DOMAIN=cafe-delicacy-restaurant.com
#   export SSH_KEY=./cafe.pem
#   bash deploy-dual-env.sh

set -e

EC2_IP="${EC2_IP:?Set EC2_IP=your.ec2.static.ip}"
DOMAIN="${DOMAIN:?Set DOMAIN=your.domain.com}"
SSH_KEY="${SSH_KEY:-cafe.pem}"
EC2_USER="${EC2_USER:-ec2-user}"
APP_DIR="${APP_DIR:-restaurant-cafe}"

echo "🚀 Deploying Prod + Dev on same EC2"
echo "   EC2: $EC2_IP | Domain: $DOMAIN"
echo "   Prod: https://app.$DOMAIN | Dev: https://dev.$DOMAIN"
echo ""

run_on_ec2() {
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$EC2_USER@$EC2_IP" "$@"
}

# Step 1: Ensure repo is up to date
echo "📂 Step 1: Pull latest code..."
run_on_ec2 << EOF
cd ~
[ -d $APP_DIR ] && cd $APP_DIR && git pull origin main || { echo "Clone repo first"; exit 1; }
cd $APP_DIR
EOF

# Step 2: Start Prod stack (exclude nginx - we use host nginx for both)
echo "🐳 Step 2: Start Prod stack (db, redis, api only)..."
run_on_ec2 << 'REMOTE'
cd restaurant-cafe
docker compose -f docker-compose.yml stop nginx 2>/dev/null || true
docker compose -f docker-compose.yml up -d db redis api
sleep 5
docker compose ps
REMOTE

# Step 3: Create .env.dev from template
echo "⚙️ Step 3: Configure dev environment..."
run_on_ec2 << EOF
cd $APP_DIR
[ -f .env.dev ] || cp .env.dev.example .env.dev
sed -i.bak "s|YOUR_DOMAIN|$DOMAIN|g" .env.dev 2>/dev/null || true
sed -i.bak "s|YOUR_DEV_EC2_IP|$EC2_IP|g" .env.dev 2>/dev/null || true
grep -E "API_URL|FRONTEND_URL" .env.dev || true
EOF

# Step 4: Start Dev stack (separate project name)
echo "🐳 Step 4: Start Dev stack..."
run_on_ec2 << 'REMOTE'
cd restaurant-cafe
export \$(grep -v '^#' .env.dev | xargs)
docker compose -p rkellite-dev -f docker-compose.dev.yml --env-file .env.dev build --no-cache
docker compose -p rkellite-dev -f docker-compose.dev.yml --env-file .env.dev up -d
sleep 15
docker compose -p rkellite-dev ps
REMOTE

# Step 5: Configure Nginx for both prod and dev
echo "🌐 Step 5: Configure Nginx..."
run_on_ec2 << EOF
cd $APP_DIR
# Backup existing nginx config
sudo cp /etc/nginx/conf.d/cafe-delicacy.conf /etc/nginx/conf.d/cafe-delicacy.conf.bak 2>/dev/null || true

# Create dual-env config (HTTP - update DOMAIN placeholder)
sudo tee /etc/nginx/conf.d/rkellite-dual.conf > /dev/null << NGINX
# Prod + Dev - generated by deploy-dual-env.sh
server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN app.$DOMAIN api.$DOMAIN;
    location /api/ {
        proxy_pass http://127.0.0.1:5001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
    location / {
        proxy_pass http://127.0.0.1:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
    }
}
server {
    listen 80;
    server_name dev.$DOMAIN dev-app.$DOMAIN;
    location /api/ {
        proxy_pass http://127.0.0.1:5005/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
    location / {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
    }
}
NGINX

# Remove old single-env config to avoid conflicts (or rename)
sudo rm -f /etc/nginx/conf.d/cafe-delicacy.conf 2>/dev/null || true

sudo nginx -t && sudo systemctl reload nginx
echo "Nginx reloaded"
EOF

echo ""
echo "✅ Dual-environment deployment complete!"
echo ""
echo "🌐 Access:"
echo "   Prod:  http://app.$DOMAIN  (or http://$EC2_IP)"
echo "   Dev:   http://dev.$DOMAIN  (or http://$EC2_IP - add dev subdomain in DNS)"
echo ""
echo "📋 DNS: Add A record: dev.$DOMAIN -> $EC2_IP"
echo "🔒 SSL: sudo certbot certonly --nginx -d dev.$DOMAIN"
echo ""
echo "📝 Logs:"
echo "   Prod: ssh -i $SSH_KEY $EC2_USER@$EC2_IP 'cd $APP_DIR && docker compose logs -f'"
echo "   Dev:  ssh -i $SSH_KEY $EC2_USER@$EC2_IP 'cd $APP_DIR && docker compose -p rkellite-dev -f docker-compose.dev.yml logs -f'"
